<?php get_header(); ?>
<main>
<section class="hero"><div class="container hero-grid"><div><span class="eyebrow"><i></i> برقِ مطمئن، انتخابِ هوشمند</span><h1>برای هر اتصال،<br><strong>بهترین انتخاب</strong> را دارید.</h1><p>تجهیزات برق و روشنایی را از میان برندهای معتبر، با مشاوره تخصصی و ارسال سریع انتخاب کنید.</p><div class="hero-cta"><a class="button button-primary" href="#products">مشاهده محصولات ←</a><a class="button button-outline" href="#categories">دسته‌بندی‌ها</a></div></div><div class="hero-art" aria-hidden="true"><span class="orb one"></span><span class="orb two"></span><div class="product-device"><span class="device-status"></span><div class="device-label">SMART POWER</div><div class="device-number">220<span>V</span></div><div class="device-lines"><span></span><span></span><span></span></div></div></div></div></section>
<section class="benefits"><div class="container benefit-grid"><div class="benefit"><span class="benefit-icon">⚡</span>بیش از ۱۰,۰۰۰ کالای تخصصی</div><div class="benefit"><span class="benefit-icon">◈</span>تضمین اصالت و کیفیت کالا</div><div class="benefit"><span class="benefit-icon">▣</span>ارسال سریع به سراسر ایران</div><div class="benefit"><span class="benefit-icon">☏</span>مشاوره پیش از خرید</div></div></section>
<section class="section container" id="categories"><div class="section-heading"><div><h2>هر آنچه برای برق نیاز دارید</h2><p>دسته‌بندی‌های منتخب واتکس شاپ</p></div><a class="link-more" href="#products">مشاهده همه ←</a></div><div class="categories"><a class="category" href="#products"><div class="category-icon">💡</div><h3>روشنایی</h3><span>لامپ، پنل و پروژکتور</span><b class="category-arrow">←</b></a><a class="category" href="#products"><div class="category-icon">🔌</div><h3>کلید و پریز</h3><span>مدرن و کلاسیک</span><b class="category-arrow">←</b></a><a class="category" href="#products"><div class="category-icon">⚙️</div><h3>تجهیزات صنعتی</h3><span>کنتاکتور و محافظ</span><b class="category-arrow">←</b></a><a class="category" href="#products"><div class="category-icon">🏠</div><h3>خانه هوشمند</h3><span>کنترل و اتوماسیون</span><b class="category-arrow">←</b></a></div></section>
<section class="section product-section" id="products"><div class="container"><div class="section-heading"><div><h2>محبوب‌ترین‌های واتکس</h2><p>انتخاب کاربران برای یک خرید مطمئن</p></div><a class="link-more" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : '#'); ?>">همه محصولات ←</a></div><div class="filters"><button class="filter active">همه محصولات</button><button class="filter">روشنایی</button><button class="filter">کلید و پریز</button><button class="filter">تجهیزات برق</button><button class="filter">خانه هوشمند</button></div><div class="products"><?php if (function_exists('wc_get_products')) { $items = wc_get_products(['limit'=>4,'status'=>'publish','orderby'=>'popularity']); foreach ($items as $item) : ?><article class="product"><a href="<?php echo esc_url(get_permalink($item->get_id())); ?>"><div class="product-image"><?php echo $item->get_image('woocommerce_thumbnail'); ?></div><h3><?php echo esc_html($item->get_name()); ?></h3><span class="brand-name"><?php echo esc_html(wc_get_product_category_list($item->get_id())); ?></span><div class="price-row"><span class="price"><?php echo wp_kses_post($item->get_price_html()); ?></span></div></a></article><?php endforeach; } else { $demo=[['💡','لامپ هوشمند ۹ وات فیلیپس','۴۸۵,۰۰۰'],['🔌','کلید و پریز مدرن پارت','۲۲۸,۰۰۰'],['⚡','محافظ برق دیجیتال تیراژه','۱,۱۲۰,۰۰۰'],['🔆','پنل سقفی ۱۸ وات پارس','۳۴۲,۰۰۰']]; foreach($demo as $d): ?><article class="product"><span class="badge">موجود</span><button class="wish">♡</button><div class="product-image"><span><?php echo $d[0]; ?></span></div><h3><?php echo $d[1]; ?></h3><span class="brand-name">انتخاب واتکس</span><div class="price-row"><span class="price"><?php echo $d[2]; ?> <small>تومان</small></span><button class="add">افزودن +</button></div></article><?php endforeach; } ?></div></div></section>
<section class="campaign container" id="offer"><div class="campaign-content"><span class="eyebrow">پیشنهاد محدود این هفته</span><h2>هوشمندسازی خانه،<br>با قیمت هوشمندانه</h2><p>تا ۳۰٪ تخفیف روی محصولات منتخب خانه هوشمند</p><div class="timer"><span class="time">۰۲<small>روز</small></span><span class="time">۱۸<small>ساعت</small></span><span class="time">۴۵<small>دقیقه</small></span></div><a class="button button-primary" href="#products">مشاهده پیشنهادها ←</a></div><div class="campaign-art" aria-hidden="true"><div class="cable"></div><div class="plug"><div class="plug-dots"><span></span><span></span><span></span></div></div></div></section>
</main>
<?php get_footer(); ?>
